version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESS_PASSWORD: ${DB_PASSWORD}
      POSTGRESS_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data